spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudstudy?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: yangyihi2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: bookservice
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 9184d579-2274-4e20-8b01-e5834af2425a
    sentinel:
      transport:
        dashboard: localhost:8858
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: c832eb81-a1ed-450b-9fb9-cfb0bd8671d4
      username: nacos
      password: nacos
  # 配置
  config:
    type: nacos
    nacos:
      namespace: c832eb81-a1ed-450b-9fb9-cfb0bd8671d4
      username: nacos
      password: nacos


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.yanghi.study.bean # 配置具体包下类具有默认别名

