server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudstudy?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: yangyihi2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: borrow-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 9184d579-2274-4e20-8b01-e5834af2425a
    loadbalancer:
      enabled: true
    sentinel:
      transport:
        dashboard: localhost:8858
      # 关闭Context收敛，这样被监控方法可以进行不同链路的单独控制
      web-context-unify: false
      block-page: /return/blocked

feign:
  sentinel:
    enabled: true

seata:
  registry:
    type: nacos
    nacos:
      namespace: c832eb81-a1ed-450b-9fb9-cfb0bd8671d4
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      namespace: c832eb81-a1ed-450b-9fb9-cfb0bd8671d4
      username: nacos
      password: nacos

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.yanghi.start.bean # 配置具体包下类具有默认别名